org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=34
android.usePre21CompileJavaWorkaround=true

# App Signing (Placeholders for CI/CD or local release builds)
MAVUNO_RELEASE_STORE_FILE=../keystore/mavuno-release.jks
MAVUNO_RELEASE_STORE_PASSWORD=mavuno-production-2026
MAVUNO_RELEASE_KEY_ALIAS=mavuno-key
MAVUNO_RELEASE_KEY_PASSWORD=mavuno-production-2026

# R8 Optimization
android.enableR8.fullMode=true
