"""Add hardware audit table v3

Revision ID: 160f241d2f06
Revises: b2542c00ce9c
Create Date: 2026-06-05 19:54:14.976212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160f241d2f06'
down_revision: Union[str, Sequence[str], None] = 'b2542c00ce9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('firmware_v', sa.String(length=16), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('signal_rssi', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_ping_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hardware_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_audit_farm_id'), ['farm_id'], unique=False)

    with op.batch_alter_table('farmer_profiles', schema=None) as batch_op:
        batch_op.alter_column('planting_date',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('current_stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'Land Prep'"))
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending_kyc'"))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('verification_metadata')

    with op.batch_alter_table('farmer_profiles', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending_kyc'"))
        batch_op.alter_column('current_stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'Land Prep'"))
        batch_op.alter_column('planting_date',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('hardware_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_audit_farm_id'))

    op.drop_table('hardware_audit')
    # ### end Alembic commands ###
