"""Initial schema

Revision ID: b2542c00ce9c
Revises: 
Create Date: 2026-04-28 22:51:17.752618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2542c00ce9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immutable_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=False),
    sa.Column('curr_hash', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immutable_ledger_curr_hash'), 'immutable_ledger', ['curr_hash'], unique=False)
    op.create_table('training_modules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('buyer_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('crops_json', sa.Text(), nullable=False),
    sa.Column('floor_ugx', sa.Integer(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('farmer_name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('crop', sa.String(length=50), nullable=False),
    sa.Column('acres', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('collection_hub', sa.String(length=64), nullable=False),
    sa.Column('discipline', sa.Float(), nullable=False),
    sa.Column('drought_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_farmer_profiles_district'), 'farmer_profiles', ['district'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('farmer_certifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.BigInteger(), nullable=False),
    sa.Column('expiry_at', sa.BigInteger(), nullable=True),
    sa.Column('ledger_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_certifications_farm_id'), 'farmer_certifications', ['farm_id'], unique=False)
    op.create_table('market_offers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('crop', sa.String(length=32), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('floor_ugx', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('total_amount_ugx', sa.Integer(), nullable=False),
    sa.Column('payment_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settled_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_farm_id'), 'posts', ['farm_id'], unique=False)
    op.create_table('soil_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('n_mg_kg', sa.Float(), nullable=False),
    sa.Column('p_mg_kg', sa.Float(), nullable=False),
    sa.Column('k_mg_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_telemetry_farm_id'), 'soil_telemetry', ['farm_id'], unique=False)
    op.create_index(op.f('ix_soil_telemetry_timestamp'), 'soil_telemetry', ['timestamp'], unique=False)
    op.create_table('yield_priorities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('yps', sa.Integer(), nullable=False),
    sa.Column('kg_allocated', sa.Integer(), nullable=False),
    sa.Column('kg_remaining', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('aggregation_point', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=True),
    sa.Column('last_msg_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['market_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_flags',
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('reactions',
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id', 'emoji')
    )
    op.create_table('settlements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=False),
    sa.Column('amount_ugx', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ledger_hash', sa.String(length=128), nullable=False),
    sa.Column('settled_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['market_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('settlements')
    op.drop_table('reactions')
    op.drop_table('post_flags')
    op.drop_table('conversations')
    op.drop_table('yield_priorities')
    op.drop_index(op.f('ix_soil_telemetry_timestamp'), table_name='soil_telemetry')
    op.drop_index(op.f('ix_soil_telemetry_farm_id'), table_name='soil_telemetry')
    op.drop_table('soil_telemetry')
    op.drop_index(op.f('ix_posts_farm_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('payment_batches')
    op.drop_table('market_offers')
    op.drop_index(op.f('ix_farmer_certifications_farm_id'), table_name='farmer_certifications')
    op.drop_table('farmer_certifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_farmer_profiles_district'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_immutable_ledger_curr_hash'), table_name='immutable_ledger')
    op.drop_table('immutable_ledger')
    # ### end Alembic commands ###
